version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: lipamdogo_postgres
    restart: always
    environment:
      POSTGRES_USER: lmm_admin
      POSTGRES_PASSWORD: 1234pass
      POSTGRES_DB: lipamdogo_database
    ports:
      - "5432:5432"
    volumes:
      - lipamdogo_postgres_data:/var/lib/postgresql/data
#    to check it out visit  C:\ProgramData\Docker\volumes\lmm_postgres_data\_data

  adminer:
    image: ghcr.io/shyim/adminerevo:latest
    restart: always
    ports:
      - 8080:8080
volumes:
  lipamdogo_postgres_data: