spring.application.name=dailymotivation
server.port=8081
postgresql.url=jdbc:postgresql://localhost:5432/lmm_database
postgresql.username=lmm_admin
postgresql.password=1234$ecureP@$$
postgresql.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect